Name: BWF
Repo: ""
Version: master
Dest: /home/gqzcl/文档/BWF
Module: BWF
DisableInlineCommands: false
DisableNpmInstall: false
NpmBuildScriptName: build
Watcher:
    Disable: false
    Backend:
        - .go
        - .mod
        - .yml
        - .toml
        - .tml
        - .ini
        - .proto
    Frontend:
        - .html
        - .htm
        - .svelte
        - .md
        - .js
        - .ts
        - .jsx
        - .tsx
        - .css
        - .scss
        - .less
        - .json
        - .proto
    IgnoreDirs:
        - .github
        - .github/*
        - uploads
        - uploads/*
LiveReload:
    Disable: false
    Port: 35729
Files:
    - app
    - app/StartIris.go
    - doc
    - doc/IRIS_start.md
    - doc/docker_use.md
    - doc/notes.md
    - doc/setting.md
    - go.mod
    - go.sum
    - main.go
    - newdocker
    - newdocker/Dockerfile
    - views
    - views/form.html
    - views/hello.html
BuildFiles: []
MD5PackageJSON: []
